axis_linear: 1
scale_linear: 0.7
#scale_linear: 5.0
scale_linear_turbo: 1.5
#scale_linear_turbo: 10.0

axis_angular: 0
# scale_angular: 0.4
scale_angular: 1.0

enable_button: 6  # RB shoulder button
enable_turbo_button: 7  # LB shoulder button
