footprint: [[-0.9652, -0.9525], [-0.9652, 0.9525], [0.7824177392, 0.9525], [1.4910104038, 0.0], [0.7824177392, -0.9525]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: r2300_node/scan_0, inf_is_valid: true, min_obstacle_height: -0.1}

inflation:
    inflation_radius: 1.0
